#!/usr/bin/env python3
'''
Check salt's local sdb store and if the countdown was initiated, reduce the
counter by one. If the counter has reached 60, kick off a global highstate.
'''
import salt.config
import subprocess
import time
from salt.utils.sdb import sdb_get, sdb_set

opts = salt.config.minion_config('/etc/salt/minion')
tick = int(sdb_get('sdb://localsdb/hst_tick', opts))

if tick:
    if tick > 0:
        sdb_set('sdb://localsdb/hst_tick', tick - 1, opts)
    if tick == 7:
        p = subprocess.Popen(
                ['/usr/bin/salt-run', 'state.orch', '_orchestrate.global_highstate'],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE)
        stdout, stderr = p.communicate()
        if stdout or stderr:
            with open('/var/log/salt/global_highstate.log', 'a') as fh:
                fh.write('{}\n'.format(time.strftime("%c")))
                if stdout:
                    fh.write('{}\n'.format(stdout))
                if stderr:
                    fh.write('{}\n'.format(stderr))
                fh.close()
