#!/bin/bash
max="${1:-9}"

# Print header (space, range{1..max})
printf '  '
for ((i=1; i<=$max; i++)); do
	printf '%7s' "$i"
done
printf '\n'

for ((row=1; row<=$max; row++)); do
	# Print multiplier
	printf "%-2s" "$row"
	for ((col=1; col<=$max; col++)); do
		# Print products
		printf '%7s' "$(($row * $col))"
	done
	printf '\n'
done
